"""empty message

Revision ID: 33b59e8817f3
Revises: 6d95a0caf3a5
Create Date: 2023-01-05 19:51:36.097928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33b59e8817f3'
down_revision = '6d95a0caf3a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rental', sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rental', 'id')
    # ### end Alembic commands ###
