"""empty message

Revision ID: 9887919917ce
Revises: 33b59e8817f3
Create Date: 2023-01-07 17:25:51.501164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9887919917ce'
down_revision = '33b59e8817f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rental', sa.Column('check_out_status', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rental', 'check_out_status')
    # ### end Alembic commands ###
