"""empty message

Revision ID: edd24821936b
Revises: 18985b006dc6
Create Date: 2023-01-04 11:57:56.077788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edd24821936b'
down_revision = '18985b006dc6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customer', 'phone',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('customer', 'postal_code',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('video', 'release_date',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('video', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('video', 'total_inventory',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('video', 'total_inventory',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('video', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('video', 'release_date',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('customer', 'postal_code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('customer', 'phone',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
